name: find_tutors
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter:
  transparent_image: "^0.1.0"
  cached_network_image: "^0.4.1"
  rxdart:
  flutter_masked_text:
  bubble_tab_indicator: "^0.1.3"
  flutter_slidable: "^0.4.1"
  http:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/app-icon.png
    - assets/images/slanted_menu.png
    - assets/images/forgot_password.png
    
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
