name: find_tutors
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
   sdk: flutter
  intl: ^0.15.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter:
  transparent_image: "^0.1.0"
  # cached_network_image: "^0.4.1"
  rxdart:
  flutter_masked_text:
  bubble_tab_indicator: "^0.1.3"
  flutter_slidable: "^0.4.1"
  http:
  path: 
  image_picker:
  cloud_firestore: ^0.7.3
  firebase_storage: ^1.0.2
  firebase_auth: ^0.5.19
  firebase_core: ^0.2.5
  google_sign_in:
  flutter_facebook_login: ^1.1.1
  sqflite:
  url_launcher:



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/app-icon.png
    - assets/images/sub_icon.png
    - assets/images/slanted_menu.png
    - assets/images/forgot_password.png
    - assets/images/Map.png
    - assets/locale/localization_en.json
    - assets/locale/localization_km.json
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/Kantumruy-Regular.ttf
        - asset: assets/fonts/Kantumruy-Bold.ttf
          weight: 700
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
